# Site settings
title: "Chanbin Lee - Software Engineer & Photographer"
email: 0415cbl@gmail.com
description: "Personal website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evertokki.github.io" # Replace with your GitHub username

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Site author
author:
  name: Chanbin Lee
  email: 0415cbl@gmail.com